#!/bin/bash

# Public IP
mypublic-ip(){
response=$(curl -s "https://api.myip.com/")
ip=$(echo $response |jq -r '.ip')
country=$(echo $response |jq -r '.country')

echo "IP:       $ip"
echo "Country:  $country"
}

# Arch Chroot
arch(){
    banner=$(figlet "Starting...")
    echo "$banner"
    sleep 1
    sudo mount --bind /mnt/arch /mnt/arch
    sudo /mnt/arch/bin/arch-chroot /mnt/arch

    banner_off=$(figlet "Closing...")
    echo "$banner_off"
    sleep 1
    sudo umount /mnt/arch
    sleep 1
    duf /
}

# Create and go 
mkcd(){
    mkdir -p $1
    cd $1
}

# Stream Test
streamscan(){
    while read -r url; do
        if ! timeout 30s ffprobe "$url" 2>&1 |grep -i "input"; then
            echo "$url = timeout, no input..."
        fi
    done < "$1"
}

# History + grep
hg(){
    history | grep "$1";
}


# Cheat curl cht.sh/:styles-demo
cheat() {
  if [[ "$1" ]]; then 
    curl "https://cheat.sh/$1"
  else
    echo 'command not exit'
  fi
}

# Simplified git commit
gc() {
  if [[ -n "$1" ]]; then
    git commit -m "$*"
  else
    echo "error: no commit message provided"
    return 1
  fi
}

# Git add, commit and push
gpa() {
  git add -A
  git commit -m "${*^}"
  git push
}

# Rename files to lower case and replace spaces to -
mvlower() {
  for file in *; do
    newname="${file,,}"
    newname="${newname//[áãâ]/a}"
    newname="${newname//[é]/e}"
    newname="${newname//[í]/i}"
    newname="${newname//[ó]/o}"
    newname="${newname//[ú]/u}"
    newname="${newname//[ç]/c}"
    newname="${newname//\(/}"
    newname="${newname//\)/}"
    newname="${newname// /-}"
    mv "$file" "$newname" >/dev/null
  done
}

# Rename files to upper case and replace spaces to -
mvupper() {
  for file in *; do
    newname="${file^^}"
    newname="${file//[ÁÃÂ]/A}"
    newname="${file//[É]/E}"
    newname="${file//[Í]/I}"
    newname="${file//[Ó]/O}"
    newname="${file//[Ú]/U}"
    newname="${file//[Ç]/C}"
    newname="${newname// /-}"
    mv "$file" "$newname" >/dev/null
  done
}
